spring.application.name=RozgaarMandi
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

auth.enpoints.public=/public/login,/public/signUp,/h2-console
jwt.secret=AHDKFJHKSDJF3749349HDJHFJHD8374873948KHKLHDF837947239847KJHSDAFKJHSDf0934092309KJDHFJKSDHFLSHDJKSDHFKJBSDLBKVJHKSDHFIUAGSFIUGEFIUGEIFUGFKJSBDFKJ