server.port:9120
spring.application.name=RozgaarMandi
spring.datasource.url=jdbc:postgresql://localhost:5432/Rozgaarmandi
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Omsa@199824
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

auth.enpoints.public=/public/login,/public/signUp,/h2-console
jwt.secret=AHDKFJHKSDJF3749349HDJHFJHD8374873948KHKLHDF837947239847KJHSDAFKJHSDf0934092309KJDHFJKSDHFLSHDJKSDHFKJBSDLBKVJHKSDHFIUAGSFIUGEFIUGEIFUGFKJSBDFKJ[